"""Add password column to candidates table

Revision ID: 7678168d157f
Revises: 92cd320a14cb
Create Date: 2025-03-21 22:25:43.352958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7678168d157f'
down_revision: Union[str, None] = '92cd320a14cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'password')
    # ### end Alembic commands ###
