version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-app:/app
    environment:
      - DATABASE_URL=sqlite:///app.db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 